<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'e.g. http://yourdomain/pad/' => '',
    'API Connection successful!' => 'اتصال موفق API!',
    'Back to modules' => 'بازگشت‌ به ماژول‌‌ها',
    'Could not connect to API!' => 'اتصال به API برقرار نشد!',
    'Current Status:' => 'وضعیت کنونی:',
    'Notes Module Configuration' => 'تنظیمات ماژول یادداشت',
    'Please read the module documentation under /protected/modules/notes/docs/install.txt for more details!' => 'لطفا برای جزئیات بیشتر مستند ماژول را در /protected/modules/notes/docs/install.txt مطالعه کنید!',
    'Save & Test' => 'ذخیره و آزمایش',
    'The notes module needs a etherpad server up and running!' => 'ماژول یادداشت نیاز به یک سرور در حال کار etherpad دارد!',
];
