<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'e.g. http://yourdomain/pad/' => '',
    'API Connection successful!' => 'Connessione API avvenuta con successo!',
    'Back to modules' => 'Indietro ai moduli',
    'Could not connect to API!' => 'Non posso effettuare la connessione API',
    'Current Status:' => 'Stato corrente:',
    'Notes Module Configuration' => 'Configurazione del modulo delle note',
    'Please read the module documentation under /protected/modules/notes/docs/install.txt for more details!' => 'Per favore leggi il modulo della documentazione in /protected/modules/notes/docs/install.txt per maggiori dettagli!',
    'Save & Test' => 'Salva e testa',
    'The notes module needs a etherpad server up and running!' => 'Il modulo delle note ha bisogno di un serve su cui è attivo etherpad!',
];
