<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'e.g. http://yourdomain/pad/' => '',
    'API Connection successful!' => 'API соединение прошло успешно!',
    'Back to modules' => 'Назад к модулям',
    'Could not connect to API!' => 'Не удалось соединение с API!',
    'Current Status:' => 'Текущий статус:',
    'Notes Module Configuration' => 'Конфигурация модуля Заметок',
    'Please read the module documentation under /protected/modules/notes/docs/install.txt for more details!' => 'Пожалуйста прочитайте докуметацию к модулю /protected/modules/notes/docs/install.txt для получения дополнительной информации',
    'Save & Test' => 'Сохранить и протестировать',
    'The notes module needs a etherpad server up and running!' => 'Для модуля заметок необходим работающий сервер Etherpad',
];
