<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'e.g. http://yourdomain/pad/' => '',
    'API Connection successful!' => '¡Conexión con éxito con la API!',
    'Back to modules' => 'Volver a módulos',
    'Could not connect to API!' => '¡No se puedo conectar con la API!',
    'Current Status:' => 'Estado actual:',
    'Notes Module Configuration' => 'Configuración del módulo de notas',
    'Please read the module documentation under /protected/modules/notes/docs/install.txt for more details!' => 'Por favor, lee la documentación del módulo en /protected/modules/notes/docs/install.txt para mas detalles.',
    'Save & Test' => 'Guardar y probar',
    'The notes module needs a etherpad server up and running!' => '¡Este módulo de notas necesita un servidor Etherpad listo y funcionando!',
];
