<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'e.g. http://yourdomain/pad/' => '',
    'API Connection successful!' => 'APIの接続に成功！',
    'Back to modules' => 'モジュールへ戻る',
    'Could not connect to API!' => 'APIに接続できませんでした！',
    'Current Status:' => '現在のステータス：',
    'Notes Module Configuration' => 'ノートモジュールの設定',
    'Please read the module documentation under /protected/modules/notes/docs/install.txt for more details!' => '詳細については、下の/protected/modules/notes/docs/install.txtモジュールのドキュメントを読んでください！',
    'Save & Test' => '保存＆テスト',
    'The notes module needs a etherpad server up and running!' => 'ノートモジュールはEtherPadサーバーが稼働中である必要があります！',
];
