<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'e.g. http://yourdomain/pad/' => '',
    'API Connection successful!' => 'API prijungimas pavyko!',
    'Back to modules' => 'Atgal į modulius',
    'Could not connect to API!' => 'Nepavyko prisijungti prie API!',
    'Current Status:' => 'Dabartinis statusas:',
    'Notes Module Configuration' => 'Pastabų modulio konfigūracija',
    'Please read the module documentation under /protected/modules/notes/docs/install.txt for more details!' => 'Norint gauti papildomos informacijos, prašome perskaityti modulio dokumentus, esančius /protected/modules/notes/docs/install.txt',
    'Save & Test' => 'Išsaugoti ir išbandyti',
    'The notes module needs a etherpad server up and running!' => 'Pastabų modulis reikalauja, kad veiktų EtherPad serveris!',
];
