<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'e.g. http://yourdomain/pad/' => '',
    'API Connection successful!' => 'API bağlantısı başarılı!',
    'Back to modules' => 'Modüllere dön',
    'Could not connect to API!' => 'API bağlantısı sağlanamadı!',
    'Current Status:' => 'Şu an ki durum:',
    'Notes Module Configuration' => 'Not modül yapılandırma',
    'Please read the module documentation under /protected/modules/notes/docs/install.txt for more details!' => 'Lütfen "/protected/modules/notes/docs/install.txt" altındaki modül dökümanını okuyun. ',
    'Save & Test' => 'Kaydet ve test et',
    'The notes module needs a etherpad server up and running!' => 'Not modülü için çalışan bir etherpad sunucusuna ihtiyaç var!',
];
