<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'API Connection successful!' => '',
  'Could not connect to API!' => '',
  'Could not get note content!' => '',
  'Current Status:' => '',
  'Etherpad API Key' => '',
  'Integrates etherpads to the space.' => '',
  'Integrates etherpads to your space.' => '',
  'No notes found which matches your current filter(s)!' => '',
  'Note' => '',
  'Notes' => '',
  'Notes Module Configuration' => '',
  'Open full note' => '',
  'Please read the module documentation under /protected/modules/notes/docs/install.txt for more details!' => '',
  'Save' => '',
  'Save & Test' => '',
  'Save and close' => '',
  'The notes module needs a etherpad server up and running!' => '',
  'The zsso module needs a Zeros SSO server up and running!' => '',
  'There are no notes yet!' => '',
  'This is a public note (also non-members)' => '',
  'Title of your new note...' => '',
  'URL to Etherpad' => '',
  'You also need to put private/public keys in /protected/modules/zsso/keys/ !' => '',
  'created a new note' => '',
);
