<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'e.g. http://yourdomain/pad/' => '',
    'API Connection successful!' => 'Connexion à l\'API avec succès!',
    'Back to modules' => 'Retour aux modules',
    'Could not connect to API!' => 'Impossible de se connecter à l\'API!',
    'Current Status:' => 'Status courant:',
    'Notes Module Configuration' => 'Configuration du module Notes',
    'Please read the module documentation under /protected/modules/notes/docs/install.txt for more details!' => 'Veuillez lire la documentation du module sous /protected/modules/notes/docs/install.txt pour plus de détails',
    'Save & Test' => 'Enregistrer & Tester',
    'The notes module needs a etherpad server up and running!' => 'Le module de notes requiert un serveur etherpad actif!',
];
