<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'e.g. http://yourdomain/pad/' => '',
    'API Connection successful!' => 'API - Conexão bem sucedida!',
    'Back to modules' => 'Voltar aos módulos',
    'Could not connect to API!' => 'Não foi possível conectar-se a API!',
    'Current Status:' => 'Status atual:',
    'Notes Module Configuration' => 'Configuração do Módulo de Notas',
    'Please read the module documentation under /protected/modules/notes/docs/install.txt for more details!' => 'Por favor, leia a documentação do módulo em  protected/modules/notes/docs/install.txt para mais detalhes!',
    'Save & Test' => 'Salvar & Testar',
    'The notes module needs a etherpad server up and running!' => 'O módulo de notas precisa de um servidor EtherPad Up e executando!',
];
