<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'e.g. http://yourdomain/pad/' => '',
    'API Connection successful!' => 'Připojení k API bylo úspěšné!',
    'Back to modules' => 'Zpět na přehled modulů',
    'Could not connect to API!' => 'Nebylo možné se připojit k API!',
    'Current Status:' => 'Aktuální stav:',
    'Notes Module Configuration' => 'Nastavení modulu Poznámky',
    'Please read the module documentation under /protected/modules/notes/docs/install.txt for more details!' => 'Pro více informací si prosím přečtěte dokumentaci modulu v /protected/modules/notes/docs/install.txt',
    'Save & Test' => 'Uložit a vyzkoušet',
    'The notes module needs a etherpad server up and running!' => 'Modul Poznámky vyžaduje ke svému provozu běžící etherpad server!',
];
