<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'e.g. http://yourdomain/pad/' => '',
    'API Connection successful!' => 'API Verbindung erfolgreich!',
    'Back to modules' => 'Zurück zu den Modulen',
    'Could not connect to API!' => 'Konnte nicht mit der API verbinden!',
    'Current Status:' => 'Aktueller Status:',
    'Notes Module Configuration' => 'Konfiguration Notizmodul',
    'Please read the module documentation under /protected/modules/notes/docs/install.txt for more details!' => 'Bitte für weitere Details die Moduldokumentation unter /protected/modules/notes/docs/install.txt lesen!',
    'Save & Test' => 'Speichern & Testen',
    'The notes module needs a etherpad server up and running!' => 'Das Notizmodul benötigt einen intallierten und laufenden Etherpad Server!',
];
